server:
  port: ${PORT:8761}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true
  instance:
    hostname: localhost
    home-page-url: http://${eureka.instance.hostname}:${server.port}/eureka/